---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./serviceaccount.yaml
  - ./externalsecret.yaml
  - ./mcp-config.yaml
  - ./models-config.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./cnp-egress.yaml
