---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wireguard-gateway
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wireguard-gateway-config
    template:
      data:
        wg0.conf: |
          [Interface]
          Address = 10.66.0.1/24
          ListenPort = {{ .listen_port }}
          PrivateKey = {{ .private_key }}
          PostUp = iptables -t nat -A POSTROUTING -s 10.66.0.0/24 -o ens3 -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT
          PostDown = iptables -t nat -D POSTROUTING -s 10.66.0.0/24 -o ens3 -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT

          [Peer]
          # qbt-reel
          PublicKey = {{ .qbt_reel_pubkey }}
          PresharedKey = {{ .qbt_reel_psk }}
          AllowedIPs = 10.66.0.10/32

          [Peer]
          # qbt-ink
          PublicKey = {{ .qbt_ink_pubkey }}
          PresharedKey = {{ .qbt_ink_psk }}
          AllowedIPs = 10.66.0.11/32
  dataFrom:
    - extract:
        key: wg-server
