---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wireguard-gateway
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-cluster-vault
  target:
    name: wireguard-gateway-config
    template:
      data:
        wg0.conf: |
          [Interface]
          Address = 10.66.0.1/24, fd66::1/64
          ListenPort = {{ .listen_port }}
          PrivateKey = {{ .private_key }}
          PostUp = iptables -t nat -A POSTROUTING -s 10.66.0.0/24 -o ens3 -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A PREROUTING -i ens3 -p tcp --dport 51847 -j DNAT --to-destination 10.66.0.10:51847; iptables -t nat -A PREROUTING -i ens3 -p udp --dport 51847 -j DNAT --to-destination 10.66.0.10:51847; iptables -t nat -A PREROUTING -i ens3 -p tcp --dport 54182 -j DNAT --to-destination 10.66.0.11:54182; iptables -t nat -A PREROUTING -i ens3 -p udp --dport 54182 -j DNAT --to-destination 10.66.0.11:54182; ip6tables -t nat -A POSTROUTING -s fd66::/64 -o ens3 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -o wg0 -j ACCEPT; ip6tables -t nat -A PREROUTING -i ens3 -p tcp --dport 51847 -j DNAT --to-destination [fd66::10]:51847; ip6tables -t nat -A PREROUTING -i ens3 -p udp --dport 51847 -j DNAT --to-destination [fd66::10]:51847; ip6tables -t nat -A PREROUTING -i ens3 -p tcp --dport 54182 -j DNAT --to-destination [fd66::11]:54182; ip6tables -t nat -A PREROUTING -i ens3 -p udp --dport 54182 -j DNAT --to-destination [fd66::11]:54182
          PostDown = iptables -t nat -D POSTROUTING -s 10.66.0.0/24 -o ens3 -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D PREROUTING -i ens3 -p tcp --dport 51847 -j DNAT --to-destination 10.66.0.10:51847; iptables -t nat -D PREROUTING -i ens3 -p udp --dport 51847 -j DNAT --to-destination 10.66.0.10:51847; iptables -t nat -D PREROUTING -i ens3 -p tcp --dport 54182 -j DNAT --to-destination 10.66.0.11:54182; iptables -t nat -D PREROUTING -i ens3 -p udp --dport 54182 -j DNAT --to-destination 10.66.0.11:54182; ip6tables -t nat -D POSTROUTING -s fd66::/64 -o ens3 -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -D FORWARD -o wg0 -j ACCEPT; ip6tables -t nat -D PREROUTING -i ens3 -p tcp --dport 51847 -j DNAT --to-destination [fd66::10]:51847; ip6tables -t nat -D PREROUTING -i ens3 -p udp --dport 51847 -j DNAT --to-destination [fd66::10]:51847; ip6tables -t nat -D PREROUTING -i ens3 -p tcp --dport 54182 -j DNAT --to-destination [fd66::11]:54182; ip6tables -t nat -D PREROUTING -i ens3 -p udp --dport 54182 -j DNAT --to-destination [fd66::11]:54182

          [Peer]
          # qbt-reel
          PublicKey = {{ .qbt_reel_pubkey }}
          PresharedKey = {{ .qbt_reel_psk }}
          AllowedIPs = 10.66.0.10/32, fd66::10/128

          [Peer]
          # qbt-ink
          PublicKey = {{ .qbt_ink_pubkey }}
          PresharedKey = {{ .qbt_ink_psk }}
          AllowedIPs = 10.66.0.11/32, fd66::11/128
  dataFrom:
    - extract:
        key: wg-server
