---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./certificates.yaml
  - ./envoy.yaml
  - ./envoy-clusterip.yaml
  - ./envoy-tailscale.yaml
  - ./gw-public.yaml
  - ./gw-tailnet.yaml
  - ./gw-tunnel.yaml
  - ./redirect.yaml
