---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: litellm
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: litellm
  ingress:
    - toPorts:
        - ports:
            - port: "4000"
              protocol: TCP
