---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        DATABASE_URL: "postgresql://{{ .LITELLM_POSTGRES_USER }}:{{ .LITELLM_POSTGRES_PASS }}@pg-17a-rw.db.svc.cluster.local:5432/litellm"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: litellm
        INIT_POSTGRES_HOST: pg-17a-rw.db.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .LITELLM_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LITELLM_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: litellm-${CLUSTER_NAME}
    - extract:
        key: pg-17a-${CLUSTER_NAME}
