---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nautobot-db
  namespace: &namespace nautobot
  labels:
    infra.freckle.systems/post-build-variables: enabled
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: *namespace
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
    - name: barman-cloud-plugin
      namespace: cnpg-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/nautobot/db
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
