---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}${VOLSYNC_PVC_SUFFIX:=}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:=10Gi}
  storageClassName: ceph-block
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: ${APP}${VOLSYNC_PVC_SUFFIX:=}-bootstrap
