---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}${VOLSYNC_PVC_SUFFIX:=}-bootstrap
spec:
  trigger:
    manual: bootstrap-${APP}
  restic:
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID}
      runAsGroup: ${VOLSYNC_GID:=${VOLSYNC_UID}}
      fsGroup: ${VOLSYNC_FSGROUP:=${VOLSYNC_UID}}
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    repository: ${APP}-volsync
    copyMethod: Snapshot
    accessModes: [ReadWriteOnce]
    capacity: ${VOLSYNC_CAPACITY:=10Gi}
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 1Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes: [ReadWriteOnce]
    cleanupCachePVC: true
    cleanupTempPVC: true
