---
apiVersion: v1
kind: Service
metadata:
  name: vllm-gpt-oss-2node-base
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: vllm-gpt-oss-2node-base
  ports:
    - name: http
      port: 8000
      targetPort: http
