---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../../../components/flux-post-build-variables
resources:
  - ./audiobookshelf.yaml
  - ./autobrr.yaml
  - ./bazarr.yaml
  - ./cross-seed.yaml
  - ./domains-externalsecrets.yaml
  - ./emby.yaml
  - ./flaresolverr.yaml
  - ./homepage.yaml
  - ./homepage-config.yaml
  - ./homepage-oidc.yaml
  - ./jellyfin.yaml
  - ./cnp-jellyfin-ingress.yaml
  - ./mousehole.yaml
  - ./plex.yaml
  - ./plextraktsync-nicole.yaml
  - ./promptbook.yaml
  - ./prowlarr.yaml
  - ./qbt-ink.yaml
  - ./qbt-reel.yaml
  - ./qui.yaml
  - ./radarr.yaml
  - ./recyclarr.yaml
  - ./sabnzbd.yaml
  - ./seerr.yaml
  - ./sonarr.yaml
  - ./sonarr-anime.yaml
  - ./tautulli.yaml
  - ./unpackerr.yaml
  - ./webhook.yaml
