---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 1h
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01
            env:
              TZ: America/Chicago
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: ${QBT_TRANSFER_PORT}
            ports:
              - name: http
                containerPort: *port
              - name: transfer
                containerPort: ${QBT_TRANSFER_PORT}
                protocol: TCP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 18Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: ${VOLSYNC_UID:=1000}
        runAsGroup: ${VOLSYNC_GID:=${VOLSYNC_UID:=1000}}
        fsGroup: ${VOLSYNC_FSGROUP:=${VOLSYNC_UID:=1000}}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: qbittorrent
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6
        ports:
          http:
            port: *port
      transfer-port:
        controller: qbittorrent
        type: LoadBalancer
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6
        labels:
          ipam.freckle.systems/lb-pool: internal
        ports:
          transfer-port:
            port: ${QBT_TRANSFER_PORT}
            protocol: TCP
    configMaps:
      config:
        data:
          .qbt.toml: |-
            [qbittorrent]
            addr = "http://localhost:80"
    persistence:
      config:
        existingClaim: ${APP}-config
      media:
        existingClaim: ${MEDIA_PVC:=store01-media}
        globalMounts:
          - path: /store01/downloads/${APP}
            subPath: ${MEDIA_SUBPATH:=downloads/${APP}}
      tmp:
        type: emptyDir
