---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snipe-it
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: snipe-it-secret
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .app_key }}"
  dataFrom:
    - extract:
        key: snipe-it-${CLUSTER_NAME}
