---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-sm
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: ${CLUSTER_NAME}-cloudflared-tunnel-token
