---
machine:
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
      - name: rdma_ucm
      - name: ib_umad
  sysctls:
    net.core.bpf_jit_enable: 1
