---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # Homebox PostgreSQL connection
        HBOX_DATABASE_DRIVER: postgres
        HBOX_DATABASE_HOST: pg-17a-rw.db.svc.cluster.local
        HBOX_DATABASE_PORT: "5432"
        HBOX_DATABASE_DATABASE: homebox
        HBOX_DATABASE_USERNAME: "{{ .HOMEBOX_POSTGRES_USER }}"
        HBOX_DATABASE_PASSWORD: "{{ .HOMEBOX_POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: homebox
        INIT_POSTGRES_HOST: pg-17a-rw.db.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .HOMEBOX_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .HOMEBOX_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: homebox-${CLUSTER_NAME}
    - extract:
        key: cloudnative-pg-${CLUSTER_NAME}
