---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app democratic-csi-apps
  namespace: &namespace democratic-csi
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-apps
      namespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/clusters/atlantis-k8s01/apps/democratic-csi
  interval: 2m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: false
