---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbt-reel-cleanup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-cluster-vault
  target:
    name: qbt-reel-cleanup
  data:
    - secretKey: QBT_URL
      remoteRef:
        key: qbt-reel-cleanup
        property: url
