---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-iscsi-democratic-csi-driver-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: truenas-iscsi-democratic-csi-driver-config
    template:
      data:
        driver-config-file.yaml: |-
          driver: freenas-iscsi
          httpConnection:
            allowInsecure: true
            apiKey: {{ .api_key }}
            apiVersion: 2
            host: 172.25.2.4
            port: 443
            protocol: https
          sshConnection:
            host: 172.25.2.4
            port: 22
            username: democraticcsi
            privateKey: {{ .ssh_private_key | quote }}
          iscsi:
            extentAvailThreshold: 0
            extentBlocksize: 512
            extentDisablePhysicalBlocksize: true
            extentInsecureTpc: true
            extentRpm: "SSD"
            extentXenCompat: false
            interface:
            namePrefix: csi-
            nameSuffix: -talos
            targetGroups:
              - targetGroupAuthGroup:
                targetGroupAuthType: None
                targetGroupInitiatorGroup: 1
                targetGroupPortalGroup: 1
            targetPortal: 172.25.2.4:3260
            targetPortals: []
          zfs:
            cli:
              sudoEnabled: true
            datasetProperties:
              "org.freenas:description": "{{ "{{" }} parameters.[csi.storage.k8s.io/pvc/namespace] {{ "}}" }}/{{ "{{" }} parameters.[csi.storage.k8s.io/pvc/name] {{ "}}" }}"
            datasetParentName: ssdstore01/k8s/iscsi/volumes
            detachedSnapshotsDatasetParentName: ssdstore01/k8s/iscsi/snapshots
            zvolBlockSize:
            zvolCompression:
            zvolDedup:
            zvolEnableReservation: false
  dataFrom:
    - extract:
        key: democratic-csi
