locals {
  # IaC admin project — hosts the WIF pool/providers and the tofu state
  # bucket. Cross-cutting identity infra.
  iac_project = "freckle-iac-438712"

  # Workload project for secrets — hosts the ESO GCP SAs, their IAM
  # bindings, and the Secret Manager resources themselves. Project ID is
  # generated by random_id and locked in state — don't try to hardcode.
  project_id = google_project.secrets.project_id

  wif_pool_id = "k8s-clusters"

  # Clusters in the WIF pool. JWKS + issuer URI are loaded from
  # var.clusters (populated by task wif:bootstrap). The provider is
  # created with inline JWKS so GCP never needs to fetch from the
  # cluster's OIDC discovery endpoint — works for fully-internal
  # control plane endpoints.

  # Secrets managed declaratively. Values are pushed via:
  #   task secrets:gen NAME=<name> [LENGTH=48]   — random alphanumeric
  #   task secrets:set NAME=<name>               — read value from stdin
  #
  # Values are NEVER stored in tofu state.
  secrets = {
  }
}

data "google_project" "this" {
  project_id = local.project_id
}

data "google_project" "iac" {
  project_id = local.iac_project
}
