locals {
  # IaC admin project — hosts the WIF pool/providers, the OIDC JWKS
  # bucket, and the tofu state bucket. Cross-cutting identity infra.
  iac_project = "freckle-iac-438712"

  # Workload project for secrets — hosts the ESO GCP SAs, their IAM
  # bindings, and the Secret Manager resources themselves. Project ID is
  # generated by random_id and locked in state — don't try to hardcode.
  project_id = google_project.secrets.project_id

  oidc_bucket = "${local.iac_project}-oidc"
  wif_pool_id = "k8s-clusters"

  # Clusters with WIF providers in the k8s-clusters pool. Before adding
  # a new entry here, run:
  #
  #   task wif:bootstrap CLUSTER=<name>
  #
  # to upload the cluster's JWKS + OIDC discovery doc to the OIDC bucket.
  # Then `tofu apply` to create the provider.
  clusters = {
    fairy-k8s01 = {}
  }

  # Per-namespace ESO bindings. Each entry creates a GCP SA, binds the
  # cluster's k8s SA to it via WIF, and grants conditional
  # secretAccessor scoped by secret name prefix `<cluster>-<namespace>-`.
  #
  # gcp_sa_id defaults to `<cluster>-<namespace>` if omitted; override
  # when adopting an existing SA.
  namespace_bindings = {
    "fairy-k8s01/tailscale" = {
      cluster   = "fairy-k8s01"
      namespace = "tailscale"
      k8s_sa    = "external-secrets-tailscale"
      gcp_sa_id = "fairy-tailscale"
    }
  }

  # Secrets managed declaratively. Values are pushed via:
  #   task secrets:gen NAME=<name> [LENGTH=48]   — random alphanumeric
  #   task secrets:set NAME=<name>               — read value from stdin
  #
  # Values are NEVER stored in tofu state.
  secrets = {
  }
}

data "google_project" "this" {
  project_id = local.project_id
}

data "google_project" "iac" {
  project_id = local.iac_project
}
