locals {
  # IaC admin project — hosts the WIF pool/providers and the tofu state
  # bucket. Cross-cutting identity infra.
  iac_project = "freckle-iac-438712"

  # Workload project for secrets — hosts the ESO GCP SAs, their IAM
  # bindings, and the Secret Manager resources themselves. Project ID is
  # generated by random_id and locked in state — don't try to hardcode.
  project_id = google_project.secrets.project_id

  wif_pool_id = "k8s-clusters"

  # Clusters in the WIF pool. JWKS + issuer URI are loaded from
  # var.clusters (populated by task wif:bootstrap). The provider is
  # created with inline JWKS so GCP never needs to fetch from the
  # cluster's OIDC discovery endpoint — works for fully-internal
  # control plane endpoints.

  # Authoritative per-cluster topology. New clusters get added here AND
  # to var.clusters (via `task wif:bootstrap`); everything else that's
  # per-cluster (API server DNS, optional CF tunnel) iterates over this.
  clusters_config = {
    "fairy-k8s01" = {
      # Control plane node IPs for the cluster's API-server DNS round-robin.
      # cn01 only for now — expand to cn01..cn05 for HA later.
      api_server_ips = ["10.189.3.16"]
      # Whether this cluster runs a Cloudflare tunnel for public ingress.
      has_cf_tunnel = true
    }
    "atlantis-k8s01" = {
      api_server_ips = ["172.26.3.5", "172.26.3.6", "172.26.3.7"]
      has_cf_tunnel  = true
    }
  }

  # Secrets managed declaratively. Values are pushed via:
  #   task secrets:gen NAME=<name> [LENGTH=48]   — random alphanumeric
  #   task secrets:set NAME=<name>               — read value from stdin
  #
  # Values are NEVER stored in tofu state.
  secrets = {
  }
}

data "google_project" "this" {
  project_id = local.project_id
}

data "google_project" "iac" {
  project_id = local.iac_project
}
