---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emby
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
  interval: 1h
  values:
    controllers:
      emby:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/emby
              tag: 4.9.3.0@sha256:7c33d88d0186ad7abcc6e53566e9db8766687daa5510cddc13094e25bc5a5dfb
            env:
              TZ: America/Chicago
            ports:
              - containerPort: &port 8096
                name: http
              - containerPort: 8920
                name: emby
              - containerPort: 7359
                protocol: UDP
                name: discovery
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /web/index.html
                    port: *port
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  periodSeconds: 5
                  failureThreshold: 30
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /web/index.html
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            resources:
              claims:
                - name: gpu
              limits:
                cpu: 8
                memory: 10Gi
              requests:
                cpu: 1
                memory: 1Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: emby
      securityContext:
        runAsNonRoot: true
        runAsUser: ${VOLSYNC_UID}
        runAsGroup: ${VOLSYNC_GID:=${VOLSYNC_UID}}
        fsGroup: ${VOLSYNC_FSGROUP:=${VOLSYNC_UID}}
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: emby
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6
        ports:
          http:
            port: 80
            targetPort: *port
          emby:
            port: 8920
            targetPort: 8920
          discovery:
            port: 7359
            protocol: UDP
    route:
      ui:
        hostnames: ["{{ .Release.Name }}.${CLUSTER_SUBDOMAIN}.freckle.media"]
        parentRefs:
          - name: tailnet
            namespace: gateway-system
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      config:
        existingClaim: ${APP:=emby}${VOLSYNC_PVC_SUFFIX:=}
        globalMounts:
          - path: /config
            subPath: config
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
      media:
        existingClaim: ${MEDIA_PVC:=store01-media}
        globalMounts:
          - path: /store01
