---
apiVersion: v1
kind: Service
metadata:
  name: vllm-gpt-oss-2node
spec:
  selector:
    app.kubernetes.io/name: vllm-gpt-oss-2node
    app.kubernetes.io/component: leader
  ports:
    - name: http
      port: 8000
      targetPort: http
