---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vllm-gpt-oss-2node
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /metrics
      relabelConfigs:
        - targetLabel: vllm_deployment
          replacement: vllm-gpt-oss-2node
  namespaceSelector:
    matchNames:
      - inference
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm-gpt-oss-2node
