---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ghcr-login.externalsecret.yaml
  - ./imagerepository-harvest.yaml
  - ./imagerepository-janet-manifests.yaml
  - ./imagepolicy-hedgehog.yaml
  - ./imagepolicy-harvest.yaml
  - ./imagepolicy-janet-manifests.yaml
  - ./imageupdateautomation.yaml
