---
apiVersion: v1
kind: Service
metadata:
  name: vllm-gpt-oss-2node-api
spec:
  selector:
    app.kubernetes.io/name: vllm-gpt-oss-2node
    app.kubernetes.io/component: leader
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vllm-gpt-oss-2node
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: vllm-gpt-oss-2node-api
      port:
        number: 8000
  tls:
    - hosts:
        - fairy-vllm
