---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
components:
  - ../../../../components/flux-post-build-variables
resources:
  - ./external-secrets.yaml
  - ./cloudflare-tunnel.yaml
