#!/usr/bin/env python3
"""Generate docs/reference/inventory.md from docs/_data/devices.yaml.

Reads the device inventory data file and produces a markdown table with
linked cells. The generated file is checked into git so local dev works
without running the script; CI runs it before zensical build.
"""

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "docs" / "_data" / "devices.yaml"
OUTPUT_FILE = REPO_ROOT / "docs" / "reference" / "inventory.md"

SITE_DOC_PATH = "../sites/{site}/"


def load_data() -> dict:
    with open(DATA_FILE) as f:
        return yaml.safe_load(f)


def build_table(data: dict) -> str:
    sites = data["sites"]
    racks = data.get("racks", {})
    devices = data["devices"]

    # Filter out decommissioned devices
    devices = [d for d in devices if d.get("status", "active") != "decommissioned"]

    # Sort by name
    devices.sort(key=lambda d: d["name"])

    # Decide whether to show the Status column — hide it if every visible
    # device is active (status absent or explicitly "active")
    statuses = {d.get("status", "active") for d in devices}
    show_status = statuses != {"active"}

    # Build rows
    rows = []
    for dev in devices:
        # Name cell — link to asset tag service if asset_tag is set
        name = dev["name"]
        if dev.get("asset_tag"):
            name_cell = f"[{name}](https://assets.nicole.dev/{dev['asset_tag']})"
        else:
            name_cell = name

        # Site cell — link to site doc page
        site_code = dev["site"]
        site_label = sites[site_code]
        site_cell = f"[{site_label}]({SITE_DOC_PATH.format(site=site_code)})"

        # Rack cell — link to rack anchor on site page, or dash if no rack
        rack_id = dev.get("rack")
        if rack_id:
            rack_key = f"{site_code}-{rack_id}"
            rack_info = racks.get(rack_key, {})
            rack_label = rack_info.get("label", rack_id)
            rack_anchor = rack_info.get("anchor", rack_id)
            rack_cell = f"[{rack_label}]({SITE_DOC_PATH.format(site=site_code)}#{rack_anchor})"
        else:
            rack_cell = "\u2014"

        # Role cell
        role_cell = dev["role"]

        # Model cell — link to model doc if available
        model = dev["model"]
        model_doc = dev.get("model_doc")
        if model_doc:
            model_cell = f"[{model}]({model_doc})"
        else:
            model_cell = model

        # Status cell
        status = dev.get("status", "active")

        if show_status:
            rows.append(f"| {name_cell} | {site_cell} | {rack_cell} | {role_cell} | {model_cell} | {status} |")
        else:
            rows.append(f"| {name_cell} | {site_cell} | {rack_cell} | {role_cell} | {model_cell} |")

    # Header
    if show_status:
        header = "| Name | Site | Rack | Role | Model | Status |"
        separator = "|------|------|------|------|-------|--------|"
    else:
        header = "| Name | Site | Rack | Role | Model |"
        separator = "|------|------|------|------|-------|"

    return "\n".join([header, separator] + rows)


def get_last_modified() -> str:
    """Get the last-modified timestamp of devices.yaml from git.

    Uses the author date of the most recent commit that touched the file.
    Falls back to the file's mtime if git history is unavailable (e.g.
    shallow clone or uncommitted file).
    """
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%aI", "--", str(DATA_FILE)],
            capture_output=True, text=True, check=True,
            cwd=REPO_ROOT,
        )
        timestamp = result.stdout.strip()
        if timestamp:
            dt = datetime.fromisoformat(timestamp).astimezone(timezone.utc)
            return dt.strftime("%Y-%m-%d")
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        pass

    # Fallback: file mtime
    mtime = DATA_FILE.stat().st_mtime
    dt = datetime.fromtimestamp(mtime, tz=timezone.utc)
    return dt.strftime("%Y-%m-%d")


def generate_page(data: dict) -> str:
    table = build_table(data)
    last_modified = get_last_modified()

    return f"""\
---
description: Flat reference table of every device across all sites
---

<!-- This file is generated by scripts/generate-inventory.py — do not edit by hand -->

# Device Inventory

Every named device across all sites. See [Naming Conventions](naming-conventions.md)
for how device names are structured.

{table}

---

*Generated from [`docs/_data/devices.yaml`](https://github.com/nicolerenee/infra/blob/main/docs/_data/devices.yaml).
Last updated {last_modified}.*
"""


def main():
    if not DATA_FILE.exists():
        print(f"Error: {DATA_FILE} not found", file=sys.stderr)
        sys.exit(1)

    data = load_data()

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(generate_page(data))
    print(f"Generated {OUTPUT_FILE} ({len(data['devices'])} devices)")


if __name__ == "__main__":
    main()
