---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |-
          module.exports = {
              apiKey: "{{ .api_key }}",
              torznab: [
                  "http://prowlarr/7/api?apikey={{ .prowlarr_api_key }}",
                  "http://prowlarr/9/api?apikey={{ .prowlarr_api_key }}"
              ],
              sonarr: [
                  "http://sonarr/?apikey={{ .sonarr_api_key }}"
              ],
              radarr: [
                  "http://radarr/?apikey={{ .radarr_api_key }}"
              ],
              host: "0.0.0.0",
              port: 2468,
              notificationWebhookUrls: [],
              torrentClients: [
                  "qbittorrent:http://qbt-reel-app.downloaders.svc.cluster.local"
              ],
              useClientTorrents: false,
              delay: 30,
              linkCategory: "cross-seed",
              linkDirs: ["/store01/downloads/qbt-reel/cross-seed"],
              linkType: "hardlink",
              matchMode: "partial",
              skipRecheck: true,
              autoResumeMaxDownload: 52428800,
              ignoreNonRelevantFilesToResume: false,
              // default false, i enabled
              includeSingleEpisodes: true,
              includeNonVideos: false,
              /**
              * Match season packs from the individual episodes you already have.
              * https://www.cross-seed.org/docs/basics/faq-troubleshooting#my-partial-matches-from-related-searches-are-missing-the-same-data-how-can-i-only-download-it-once
              *
              * null - disabled (required if not linking)
              * 1 - must have all episodes (values below 1 requires matchMode: "partial")
              * 0.8 - must have at least 80% of the episodes
              */
              seasonFromEpisodes: 1,
              fuzzySizeThreshold: 0.02,
              /**
              * Time based options below use the following format:
              * https://github.com/vercel/ms
              */
              /**
              * Exclude torrents or data first seen by cross-seed more than this long ago.
              * Examples:
              * "2 weeks" - if you want to search multiple times quickly
              * "450 days" - if you rather spread out the searches over a long period
              *
              * This value must be in the range of 2-5 times your excludeRecentSearch
              *
              * excludeOlder: "2 weeks",
              * excludeRecentSearch: "3 days",
              */
              excludeOlder: "2 weeks",
              excludeRecentSearch: "3 days",
              action: "inject",
              duplicateCategories: false,
              rssCadence: "30 minutes",
              searchCadence: "1 day",
              snatchTimeout: "30 seconds",
              searchTimeout: "2 minutes",
              searchLimit: 2500,
              blockList: [],
              /**
              * Details on dataDirs and maxDataDepth:
              * https://www.cross-seed.org/docs/tutorials/data-based-matching
              */
              dataDirs: ["/store01/Movies/Movies"],
              maxDataDepth: 2,
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: prowlarr-atlantis-k8s01
      rewrite:
        - regexp:
            source: "(.*)"
            target: "prowlarr_$1"
    - extract:
        key: radarr-atlantis-k8s01
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: sonarr-atlantis-k8s01
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
