---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiDriver:
      name: org.democratic-csi.freenas-iscsi
    controller:
      driver:
        enabled: true
        image:
          registry: ghcr.io/democratic-csi/democratic-csi
          tag: next
    driver:
      config:
        driver: freenas-iscsi
      existingConfigSecret: truenas-iscsi-democratic-csi-driver-config
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
    storageClasses:
      - name: truenas-iscsi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
