---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference
components:
  - ../../../../components/flux-post-build-variables
resources:
  - ./models-pvc.yaml
  - ./nfs-models.yaml
  - ./vllm-gpt-oss.yaml
