---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inference-models
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: inference-models
    namespace: inference
  nfs:
    path: /mnt/vault01/kubernetes/nfs/inference-models
    server: 192.168.227.224
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inference-models
spec:
  volumeName: inference-models
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
