---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rtl-mqtt-autodiscovery-mqtt-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  refreshInterval: 1h
  target:
    name: rtl-mqtt-autodiscovery-mqtt-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MQTT_USERNAME: "{{ .username }}"
        MQTT_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: mqtt-fairy-house-rtl-autodiscovery
        property: username
    - secretKey: password
      remoteRef:
        key: mqtt-fairy-house-rtl-autodiscovery
        property: password
