---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
  labels:
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app inference-apps
  namespace: &namespace inference
  labels:
    infra.freckle.systems/post-build-variables: enabled
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: nvidia-gpu-operator
      namespace: gpu-operator
    - name: external-secrets
      namespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/clusters/fairy-k8s01/apps/inference
  interval: 2m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
