---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdisco-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: netdisco-${CLUSTER_NAME}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdisco
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        NETDISCO_ADMIN_USER: "{{ .admin_user }}"
        NETDISCO_ADMIN_PASS: "{{ .admin_pass }}"
        NETDISCO_RO_COMMUNITY: "{{ .snmp_community }}"
  dataFrom:
    - extract:
        key: netdisco-${CLUSTER_NAME}
