---
apiVersion: v1
kind: Service
metadata:
  name: netdisco
spec:
  selector:
    app.kubernetes.io/name: netdisco
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 5000
      targetPort: http
