name: docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - docs/**
      - scripts/generate-inventory.py
      - scripts/generate-llms-txt.py
      - zensical.toml
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - uses: actions/checkout@v5
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x
      - run: pip install pyyaml zensical
      - run: python scripts/generate-inventory.py
      - run: zensical build --clean
      - run: python scripts/generate-llms-txt.py
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
        id: deployment
