---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hedgehog-db-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-cluster-vault
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        # Ceph RGW doesn't enforce regions, but the AWS SDK requires a value
        # to sign requests. Static is fine here.
        s3-region: "us-east-1"
  dataFrom:
    - extract:
        key: hedgehog-db
